name: Deploy to VPS
on: 
    push:
        branches:
            - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.7
        env:
          VPS_USER_PASSWORD: ${{ secrets.VPS_USER_PASSWORD }}
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
        with: 
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_USER_PASSWORD }}
          script: |
            # Aller dans le répertoire du projet
            cd ~/End-of-studyProject/PlatformCRM
            
            # Pull les dernières modifications depuis Git
            git pull origin develop
            
            # Arrêter les conteneurs existants
            docker compose down
            
            # Démarrer les services avec docker-compose
            docker compose up -d
            
            # Mettre à jour la base de données
            npx prisma migrate deploy

            # Générer les modèles Prisma
            npx prisma generate

            # Redémarrer les services
            pm2 restart all
            
            # Afficher les logs pour vérifier le déploiement
      